parameters:

services:
    sgl_flts.tax:
        class: %sgl_flts.tax_class%
        calls:
            - [ setDefaultGst, [%sgl_flts.tax_gst%] ]
            - [ setDefaultPst, [%sgl_flts.tax_pst%] ]
            - [ setDefaultHst, [%sgl_flts.tax_hst%] ]

    sgl_flts.form.registration:
        class: SGL\FLTSBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: sgl_fltsbundle_user_registration }

    sgl_flts.profile.form.type:
        class: SGL\FLTSBundle\Form\UserType
        tags:
            - { name: form.type, alias: sgl_fltsbundle_usertype }

    sgl_flts.image_type_extension:
        class: SGL\FLTSBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    request:
        class:  Symfony\Component\HttpFoundation\Request

    sgl_flts.sglflts_twig.extension:
        class: SGL\FLTSBundle\Twig\TwigSGLFLTSExtension
        tags:
            - { name: 'twig.extension' }

    sgl_flts.request_listener:
        class: SGL\FLTSBundle\Listeners\RequestListener
        arguments: [ '@service_container', '%sgl_flts.recent_parts_limit%' ]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
